services:
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
      volumes:
        - mongodb_data:/data/db
    
  valkey:
      image: valkey/valkey:latest
      volumes:
        - valkey_data:/usr/local/etc/valkey

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env  

  worker:
    command: ['/bin/sh','-c','rq worker --with-scheduler  --url redis://valkey:6379']
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./.env  
volumes:
  mongodb_data:
  valkey_data: